# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190624_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
