# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20190624_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.BooleanField(default=0, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18, editable=False, verbose_name='年纪'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_column='username', help_text='不要写乳名', max_length=32, unique=True, verbose_name='姓名'),
        ),
    ]
