# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 02:09
from __future__ import unicode_literals

import app01.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190624_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=app01.models.MyCharField(max_length=11, null=True),
        ),
    ]
