# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default='2019-01-01 10:10:10'),
        ),
    ]
