# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190624_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_column='username', max_length=32, unique=True),
        ),
    ]
