# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_authorbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(through='app01.AuthorBook', to='app01.Book'),
        ),
    ]
